// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/emiliopalmerini/due-draghi-5e-srd/internal/adapters/web/models"

func CollectionPage(data models.CollectionPageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"bg-white border p-2 mb-3\"><form id=\"search-form\" hx-get=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("/" + data.PageData.Collection + "/rows")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `collection.templ`, Line: 9, Col: 53}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-target=\"#rows\" hx-trigger=\"submit, keyup delay:300ms from:#q, change from:select, change from:input[type=checkbox], change from:input[type=number]\" hx-push-url=\"true\" hx-indicator=\"#loading-indicator\" class=\"flex flex-col gap-2\"><div class=\"flex items-center gap-2 flex-wrap\"><input id=\"q\" name=\"q\" placeholder=\"Cerca…\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.Query)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `collection.templ`, Line: 16, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"field flex-1\"><!-- Collection-specific filters -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = collectionFilters(data.PageData.Collection, data.PageSize).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<button class=\"btn\" type=\"submit\"><span class=\"htmx-indicator\" id=\"loading-indicator\">🔄</span> <span>Cerca</span></button></div><!-- Loading indicator --><div class=\"htmx-indicator flex items-center gap-2 text-sm text-gray-600\" id=\"loading-indicator\"><div class=\"animate-spin\">⟳</div><span>Caricamento in corso...</span></div></form></section><section class=\"bg-white border\"><div id=\"rows\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = RowsPartial(data).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = BaseLayout(data.PageData).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func collectionFilters(collection string, pageSize int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if collection == "incantesimi" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<select name=\"level\" class=\"field w-32\"><option value=\"\">Tutti i livelli</option> <option value=\"0\">Trucchetti</option> <option value=\"1\">1° Livello</option> <option value=\"2\">2° Livello</option> <option value=\"3\">3° Livello</option> <option value=\"4\">4° Livello</option> <option value=\"5\">5° Livello</option> <option value=\"6\">6° Livello</option> <option value=\"7\">7° Livello</option> <option value=\"8\">8° Livello</option> <option value=\"9\">9° Livello</option></select> <select name=\"school\" class=\"field w-36\"><option value=\"\">Tutte le scuole</option> <option value=\"abiurazione\">Abiurazione</option> <option value=\"ammaliamento\">Ammaliamento</option> <option value=\"divinazione\">Divinazione</option> <option value=\"evocazione\">Evocazione</option> <option value=\"illusione\">Illusione</option> <option value=\"invocazione\">Invocazione</option> <option value=\"necromanzia\">Necromanzia</option> <option value=\"trasmutazione\">Trasmutazione</option></select>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if collection == "mostri" || collection == "animali" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<select name=\"cr\" class=\"field w-32\"><option value=\"\">Tutti i GS</option> <option value=\"0\">GS 0</option> <option value=\"1/8\">GS 1/8</option> <option value=\"1/4\">GS 1/4</option> <option value=\"1/2\">GS 1/2</option> <option value=\"1\">GS 1</option> <option value=\"2\">GS 2</option> <option value=\"3\">GS 3</option> <option value=\"4\">GS 4</option> <option value=\"5\">GS 5</option> <option value=\"6-10\">GS 6-10</option> <option value=\"11-15\">GS 11-15</option> <option value=\"16-20\">GS 16-20</option> <option value=\"21+\">GS 21+</option></select> <select name=\"type\" class=\"field w-36\"><option value=\"\">Tutti i tipi</option> <option value=\"aberrazione\">Aberrazione</option> <option value=\"bestia\">Bestia</option> <option value=\"celestiale\">Celestiale</option> <option value=\"costrutto\">Costrutto</option> <option value=\"drago\">Drago</option> <option value=\"elementale\">Elementale</option> <option value=\"fatato\">Fatato</option> <option value=\"immondo\">Immondo</option> <option value=\"gigante\">Gigante</option> <option value=\"monolito\">Monolito</option> <option value=\"non-morto\">Non-morto</option> <option value=\"pianta\">Pianta</option> <option value=\"umanoide\">Umanoide</option></select>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if collection == "armi" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<select name=\"category\" class=\"field w-36\"><option value=\"\">Tutte le categorie</option> <option value=\"semplici\">Armi Semplici</option> <option value=\"da guerra\">Armi da Guerra</option> <option value=\"a distanza\">Armi a Distanza</option></select>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if collection == "armature" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<select name=\"category\" class=\"field w-32\"><option value=\"\">Tutti i tipi</option> <option value=\"leggera\">Leggera</option> <option value=\"media\">Media</option> <option value=\"pesante\">Pesante</option> <option value=\"scudo\">Scudo</option></select>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if collection == "oggetti_magici" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<select name=\"rarity\" class=\"field w-32\"><option value=\"\">Tutte le rarità</option> <option value=\"comune\">Comune</option> <option value=\"non comune\">Non Comune</option> <option value=\"raro\">Raro</option> <option value=\"molto raro\">Molto Raro</option> <option value=\"leggendario\">Leggendario</option> <option value=\"artefatto\">Artefatto</option></select>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<select name=\"page_size\" class=\"field w-28\"><option value=\"10\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if pageSize == 10 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, ">10/pagina</option> <option value=\"20\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if pageSize == 20 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, ">20/pagina</option> <option value=\"50\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if pageSize == 50 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, ">50/pagina</option> <option value=\"100\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if pageSize == 100 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, ">100/pagina</option></select>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
