// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LandingPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"hero\"><h1>quintaedizione.online</h1><p>Tutto il materiale base di D&amp;D 5e, in italiano e gratuito.</p></section><div class=\"collection-grid\" style=\"max-width: 720px; margin: 0 auto; padding: 0 var(--space-6) var(--space-16); grid-template-columns: 1fr 1fr;\"><a href=\"/srd\" class=\"collection-card\"><div class=\"collection-card-content\"><div class=\"collection-card-header\"><div><div class=\"collection-card-icon\" style=\"font-size: 2rem;\">📖</div><div class=\"collection-card-title\">SRD 5e</div></div></div><div class=\"collection-card-description\">Il System Reference Document completo in italiano. Incantesimi, mostri, classi, equipaggiamento e tutte le regole base.</div><div class=\"collection-card-footer\">Esplora →</div></div></a> <a href=\"/combattimenti\" class=\"collection-card\"><div class=\"collection-card-content\"><div class=\"collection-card-header\"><div><div class=\"collection-card-icon\" style=\"font-size: 2rem;\">⚔️</div><div class=\"collection-card-title\">Calcolatore Incontri</div></div></div><div class=\"collection-card-description\">Calcola il budget di PE per i tuoi incontri. Supporta le regole D&D 2014 e 2024, con browser dei mostri integrato.</div><div class=\"collection-card-footer\">Calcola →</div></div></a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = SiteLayout("Strumenti per D&D 5e in italiano", "Strumenti gratuiti per Dungeons & Dragons 5a Edizione in italiano: SRD completo e calcolatore di incontri.", "", nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
